# Generated by Django 5.0.1 on 2024-12-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='canitdad_personas',
            new_name='cantidad_personas',
        ),
        migrations.DeleteModel(
            name='EstadoReserva',
        ),
    ]
