# Generated by Django 5.0.1 on 2024-12-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasAPP', '0002_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
