# Generated by Django 5.0.1 on 2024-12-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasAPP', '0003_reserva_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasAPP.reservaestado'),
        ),
    ]
